Repository VForWaTer/metacatalog, pull requests merged in 2023-01, with the labels that each got.

#197 thesaurus_id: update keywords.csv and db revision
  metacatalog/data/keywords.csv
  metacatalog/db/revisions/__init__.py
  metacatalog/db/revisions/rev13.py
Labels: bug

#199 fix entry.details_table()
  metacatalog/models/entry.py
Labels: bug

#201 Fix CLI
  metacatalog/__version__.py
  metacatalog/command_line.py
Labels: bug

#203 Fix cli
  metacatalog/__version__.py
  metacatalog/command_line.py
Labels: bug

#226 CI publish release on tag
  .github/workflows/publish.yml
  .github/workflows/pypi-publish.yml
  RELEASE.md
  metacatalog/__version__.py
Labels: enhancement

#225 add entry to expand set
  metacatalog/util/results.py
Labels: bug, api

#230 Fix failing unittest
  metacatalog/test/test_api_add_find.py
Labels: bug, tests

#227 variable.to_dict() only include keyword if exists
  metacatalog/models/variable.py
Labels: bug

#232 ImmutableResultSet unittests
  metacatalog/test/test_result_set.py
Labels: tests

#223 rebuild entrypoint
  metacatalog/data/__init__.py
  metacatalog/metacatalog
  setup.py
Labels: bug, cli

#239 Include top-level detail of nested details
  metacatalog/models/entry.py
Labels: bug, api

#238 Fix docs CI
  .github/workflows/pages.yml
  docs/source/api/api.rst
  docs/source/api/api_add_entry.ipynb
  docs/source/cli/cli_add.ipynb
  docs/source/conf.py
  docs/source/dev/iso19115.rst
  docs/source/models/data.rst
  metacatalog/api/add.py
  metacatalog/api/catalog.py
  metacatalog/api/db.py
  metacatalog/api/find.py
  metacatalog/api/show.py
  metacatalog/ext/__init__.py
  metacatalog/ext/base.py
  metacatalog/ext/io/extension.py
  metacatalog/ext/io/interface.py
  metacatalog/models/datasource.py
  metacatalog/models/entry.py
  metacatalog/models/keyword.py
  metacatalog/models/license.py
  metacatalog/models/person.py
  metacatalog/models/variable.py
  metacatalog/util/location.py
Labels: documentation

#241 Drop field Entry.geom
  metacatalog/db/revisions/__init__.py
  metacatalog/db/revisions/rev14.py
  metacatalog/db/views/locations.sql
  metacatalog/models/entry.py
Labels: model

#244 fix nm relation Entry-Keyword
  .gitignore
  metacatalog/models/entry.py
  metacatalog/models/keyword.py
Labels: bug, api, model

#247 Mmaelicke resolve warnings
  metacatalog/test/test_db_migrations.py
  metacatalog/test/test_models_data.py
  requirements.txt
Labels: bug, api, cli
